In [2]:
import numpy as np

## Linear Algebra

In [5]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [7]:
# matrix multiplicatin
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [8]:
# find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [10]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.min(a)

1

In [12]:
np.max(a)

6

In [13]:
np.max(a, axis=0) # col wise

array([4, 5, 6])

In [15]:
np.max(a, axis=1) # row wise

array([3, 6])

In [17]:
#sum of all elements
np.sum(a)

21

In [18]:
np.sum(a, axis=1)

array([ 6, 15])

In [21]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape)
print('-----------------')
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
-----------------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
