In [1]:
import numpy as np

## load file data

In [3]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.   0.]
 [ 21.  23.  21.  54.  43.  32.  21.  43.  76.  34.]
 [ 44.  33.  22.  43.  87. 999.  98.  21. 244.  55.]]


In [4]:
print(filedata.astype('int32'))

[[  1   2   3   4   5   6   7   8   9   0]
 [ 21  23  21  54  43  32  21  43  76  34]
 [ 44  33  22  43  87 999  98  21 244  55]]


## advance indexing

In [5]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False,  True,
        False],
       [False, False, False, False,  True,  True,  True, False,  True,
         True]])

In [6]:
filedata[filedata > 50]

array([ 54.,  76.,  87., 999.,  98., 244.,  55.])

In [10]:
a = np.array([2,3,4 ,21,23,45])
print(a)
a[[0, 2, 5]]

[ 2  3  4 21 23 45]


array([ 2,  4, 45])

In [19]:
res = np.genfromtxt('data2.txt', delimiter=',').astype('int32')
print(res)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [21]:
res[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [23]:
res[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [28]:
res[[0,0,4,4,5,5], [3,4,3,4,3,4]]

array([ 4,  5, 24, 25, 29, 30])

In [29]:
res[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [30]:
res[0:4, 1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])