## Basic

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[9.0, 8.0, 3.0], [6.0, 2, 4.5]])
b

array([[9. , 8. , 3. ],
       [6. , 2. , 4.5]])

In [11]:
print(a.ndim)
print(b.ndim)

1
2


In [12]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [13]:
print(a.itemsize)

4


## Access rows, cols etc

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [22]:
# get specific element
print(a[0])
print(a[1])
print(a[0][2])
print(a[1][2])
print(a[0][-3])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]
3
10
5


In [23]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# get specif column
a[:, 2]

array([ 3, 10])

In [25]:
# [startindex: endindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

## 3-d

In [27]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
b[0,1,1]

4