## initializing

In [3]:
import numpy as np

In [25]:
# all 0's matrix
print(f"1-d \n {np.zeros((5))}")
print(f"2-d 2x2 \n {np.zeros((2,2))}")
print(f"2-d 2x3 \n {np.zeros((2,3))}")
print(f"3-d 2x3x2 \n {np.zeros((2,3,2))}")
print(f"3-d 4x3x3 \n {np.zeros((4,3,3))}")
print(f"5-d 4x3x3x3x2 \n {np.zeros((4,3,3,3,2))}")

1-d 
 [0. 0. 0. 0. 0.]
2-d 2x2 
 [[0. 0.]
 [0. 0.]]
2-d 2x3 
 [[0. 0. 0.]
 [0. 0. 0.]]
3-d 2x3x2 
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3-d 4x3x3 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
5-d 4x3x3x3x2 
 [[[[[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]]]



 [[[[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
    [0. 0.]]]


  [[[0. 0.]
    [0. 0.]
    [0. 0.]]

   [[0. 0.]
    [0. 0.]
 

In [26]:
# all 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [28]:
# any other number
np.full((2,3), 50, dtype='float32')

array([[50., 50., 50.],
       [50., 50., 50.]], dtype=float32)

In [33]:
a =  np.array(((2,3,4), (5,6,7)))
a

array([[2, 3, 4],
       [5, 6, 7]])

In [46]:
print(f"shape: {a.shape}")
print(f"size: {a.size}")
print(f"ndim: {a.ndim}")
print(f"itemsize: {a.itemsize}")


shape: (2, 3)
size: 6
ndim: 2
itemsize: 4


In [36]:
# full takes shape
np.full(a.shape, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [38]:
# full_like takes numpy array
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [50]:
# random decimal numbers
np.random.rand(2,3)

array([[0.748417  , 0.61934243, 0.73994348],
       [0.70165859, 0.09657997, 0.84308379]])

In [51]:
np.random.random_sample(a.shape)

array([[0.97471608, 0.61702041, 0.71435237],
       [0.98583378, 0.68660736, 0.02802998]])

In [55]:
# random integer numbers
np.random.randint(10, 20, size=(3,3))

array([[11, 16, 19],
       [12, 10, 19],
       [13, 14, 17]])

## identity matrix

In [57]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [65]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

## complicated matrix
1 &emsp; 1 &emsp; 1 &emsp; 1 &emsp; 1 <br>
1 &emsp; 0 &emsp; 0 &emsp; 0 &emsp; 1 <br>
1 &emsp; 0 &emsp; 9 &emsp; 0 &emsp; 1 <br>
1 &emsp; 0 &emsp; 0 &emsp; 0 &emsp; 1 <br>
1 &emsp; 1 &emsp; 1 &emsp; 1 &emsp; 1 <br>

In [66]:
res = np.ones((5,5))
res

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
middle_part = np.zeros((3,3))
middle_part

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
middle_part[1,1] = 9.0
middle_part

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [74]:
res[1:4, 1:4] = middle_part
res

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])