In [1]:
import numpy as np

## copy arrays

In [2]:
a = np.array([1,2,3])
b = a # not copy, they are same address wise

In [3]:
print(a)
print(b)

b[0] = 100

print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


In [4]:
c = a.copy()

c[0] = 300

print(a)
print(c)

[100   2   3]
[300   2   3]


In [5]:
b

array([100,   2,   3])

## arithmetics functions

In [6]:
a = np.array([1,2,3])

In [7]:
a + 2

array([3, 4, 5])

In [8]:
a * 2

array([2, 4, 6])

In [10]:
a = np.array([1,2,3, 9])
b = np.array([12,22,36, -5])
a + b

array([13, 24, 39,  4])

In [11]:
a = np.array([1,2,3])

In [12]:
a ** 2

array([1, 4, 9], dtype=int32)

In [13]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])